apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-404
  namespace: edge
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    # host 없이 규칙을 두면 "매칭 안 되는 모든 요청"을 받는 catch-all 역할
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: default-404
                port:
                  number: 80
