apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-configmap.yaml
  - 01-deployment.yaml
  - 02-service.yaml
  - 03-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: edge
  app.kubernetes.io/component: default-backend
  app.kubernetes.io/managed-by: kustomize
