apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-serviceaccount.yaml
  - 02-rbac-edge.yaml
  # - 02-rbac-app.yaml     # app 시작할 때 enable
  # - 02-rbac-infra.yaml   # infra 시작할 때 enable
  - 03-networkpolicy.yaml
  - 04-pvc.yaml
  - 05-deployment.yaml
  - 06-service.yaml
  - 07-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: cicd
  app.kubernetes.io/managed-by: kustomize
