apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-configmap-redis-conf.yaml
  - 02-pvc.yaml
  - 03-deployment.yaml
  - 04-service.yaml
  # - 05-networkpolicy.yaml   # SCG/Auth 준비되면 활성화

commonLabels:
  app.kubernetes.io/part-of: infra
  app.kubernetes.io/component: redis
  app.kubernetes.io/managed-by: kustomize
